[package]
name         = "fdapquery-expr"
description  = "LogicalPlan, LogicalExpr, DataFrame."
edition.workspace      = true
license.workspace      = true
version.workspace      = true
authors.workspace      = true
rust-version.workspace = true

[dependencies]
arrow-schema = { workspace = true }
chrono       = { workspace = true }      # NaiveDate for `LiteralDate`
fdapquery-datatypes = { version = "0.1.0", path = "../fdapquery-datatypes" }
fdapquery-catalog = { version = "0.1.0", path = "../fdapquery-catalog" }
